"""Updated groups model

Revision ID: 05e2b9fc6867
Revises: 54814d899495
Create Date: 2025-05-12 00:29:46.420396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e2b9fc6867'
down_revision = '54814d899495'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('groupIds', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'groupIds')
    # ### end Alembic commands ###