"""Fixed broken groupId schema

Revision ID: 26b8921007c4
Revises: aa6b3542caef
Create Date: 2025-05-13 10:36:44.616220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b8921007c4'
down_revision = 'aa6b3542caef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###